print("pytanie: Jak masz na imię oraz nazwisko?")
a = input("odpowiedź: ")
print("Najczęstszym sposobem spędzania wolnego czasu jest dla Ciebie:")
b = input("odpowiedź: ")
print("W jakich okolicznościach czytasz książki najczęściej?")
c = input("odpowiedź: ")
print("Jeżeli spędzasz czas wolny czytając książki, jaki jest główny powód takiego wyboru?")
d = input("odpowiedź: ")
print("Po książki w jakiej formie sięgasz najczęściej?")
e = input("odpowiedź: ")
print("Ile książek czytasz średnio w ciągu roku?")
f = input("odpowiedź: ")
print("Jak często średnio czytasz książki?")
g = input("odpowiedź: ")
print("Po jakie gatunki książek sięgasz najczęściej?")
h = input("odpowiedź: ")